language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "Everything is ready. Nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "No tests found"

script:
  - docker --version # printing the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed #building feed service docker image
  - docker build -t udagram-api-user ./udagram-api-user #building user service docker image
  - docker build -t udagram-frontend ./udagram-frontend #building frontend service docker image
  - docker build -t reverseproxy ./udagram-reverseproxy #building nginx service docker image
  - docker tag udagram-api-feed calebackom/udagram-api-feed:v1 #renaming feed docker image
  - docker tag udagram-api-user calebackom/udagram-api-user:v1 #renaming user docker image
  - docker tag udagram-frontend calebackom/udagram-frontend:v1 #renaming frontend docker image
  - docker tag reverseproxy calebackom/reverseproxy:v1 #renaming nginx docker image

after_success:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push calebackom/udagram-api-feed:v1
  - docker push calebackom/udagram-api-user:v1
  - docker push calebackom/udagram-frontend:v1
  - docker push calebackom/reverseproxy:v1
